[package]
name = "dp_client"
version = "0.1.0"
edition = "2021"
authors = ["Ari Biswas <aribiswas3@gmail.com>"]
description = "A pure-Rust implementation of a dp client as described in our paper CITE LINK"
keywords = [
  "secret-sharing",
  "Shamir",
  "cryptography",
  "secure-computation",
  "mpc",
  "differential privacy"
]
[dependencies]
rand = "0.8.5"
optimus_prime = { git = "https://github.com/abiswas3/OptimusPrime" }
openssl-sys = "0.9"
openssl = "0.10"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false